spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: localhost:8848
      config:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointment/**
        - id: consultation-service
          uri: lb://consultation-service
          predicates:
            - Path=/api/v1/consultation/**
        - id: statistics-service
          uri: lb://statistics-service
          predicates:
            - Path=/api/v1/statistics/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notification/**
